# Generated by Django 5.2 on 2025-05-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Proyek')),
                ('description', models.TextField(verbose_name='Deskripsi Singkat Proyek')),
                ('location', models.CharField(max_length=150, verbose_name='Lokasi')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('supervisor', models.CharField(max_length=100, verbose_name='Supervisor')),
                ('members', models.ManyToManyField(blank=True, to='proyek.teammember', verbose_name='Anggota Proyek')),
            ],
        ),
    ]
