# Generated by Django 5.2 on 2025-06-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Proyek')),
                ('description', models.TextField(verbose_name='Deskripsi Singkat Proyek')),
                ('location', models.CharField(max_length=150, verbose_name='Lokasi')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('supervisor', models.CharField(max_length=100, verbose_name='Supervisor')),
                ('status', models.CharField(blank=True, choices=[('Berlangsung', 'Berlangsung'), ('Stop', 'Stop'), ('Done', 'Done')], max_length=20, null=True, verbose_name='Status Proyek')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('gender', models.CharField(blank=True, choices=[('L', 'Laki - Laki'), ('P', 'Perempuan')], max_length=1, null=True, verbose_name='Jenis Kelamin')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Deskripsi Kompetensi')),
                ('role', models.TextField(blank=True, null=True, verbose_name='Deskripsi Pengalaman')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='Peran')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyek.project')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyek.teammember')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, through='proyek.ProjectMember', to='proyek.teammember'),
        ),
    ]
