# Generated by Django 5.2 on 2025-05-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyek', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='email',
        ),
        migrations.AddField(
            model_name='teammember',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alamat'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='gender',
            field=models.CharField(blank=True, choices=[('L', 'Laki - Laki'), ('P', 'Perempuan')], max_length=1, null=True, verbose_name='Jenis Kelamin'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Keahlian'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Peran'),
        ),
    ]
