# Generated by Django 5.2 on 2025-06-07 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('lokasi', models.CharField(max_length=150)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('pelaksana', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pekerjaan', to='proyek.project')),
            ],
        ),
        migrations.CreateModel(
            name='Aktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('waktu_pelaksanaan', models.DateField()),
                ('pelaksana', models.CharField(max_length=100)),
                ('pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas', to='proyek.pekerjaan')),
            ],
        ),
    ]
