# Generated by Django 5.2 on 2025-05-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyek', '0002_remove_teammember_email_teammember_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects', to='proyek.teammember'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Peran'),
        ),
    ]
