# Generated by Django 5.2 on 2025-06-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyek', '0002_pekerjaan_aktivitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pekerjaan',
            name='pelaksana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
