# Generated by Django 5.2 on 2025-06-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyek', '0003_alter_pekerjaan_pelaksana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitas',
            name='pelaksana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
