# Generated by Django 5.2 on 2025-05-07 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyek', '0003_alter_project_members_alter_teammember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktivitasPekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Aktivitas')),
                ('time', models.DateField(verbose_name='Waktu Aktivitas')),
                ('planner', models.CharField(max_length=100, verbose_name='Perancang Aktivitas')),
                ('notes', models.FileField(blank=True, null=True, upload_to='aktivitas/', verbose_name='Catatan Aktivitas')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='proyek.project')),
            ],
        ),
    ]
