# Generated by Django 5.2 on 2025-06-09 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyek', '0004_alter_aktivitas_pelaksana'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenutupanProyek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluasi', models.TextField()),
                ('tanda_tangan', models.FileField(upload_to='tanda_tangan/')),
                ('tanggal_tutup', models.DateTimeField(auto_now_add=True)),
                ('proyek', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyek.project')),
            ],
        ),
    ]
