# Generated by Django 5.2 on 2025-06-17 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyek', '0008_aktivitas_created_at_aktivitas_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrasiPesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tujuan', models.CharField(choices=[('IE', 'Intelligence Engineering'), ('IC', 'Intelligence Creation'), ('IM', 'Implementation')], max_length=2)),
                ('dikirim', models.BooleanField(default=False)),
                ('status_terakhir', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_dikirim', models.DateTimeField(auto_now_add=True)),
                ('respon', models.TextField(blank=True, null=True)),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyek.project')),
            ],
        ),
    ]
