# Generated by Django 5.2 on 2025-06-17 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyek', '0009_integrasipesan'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrasipesan',
            name='asal',
            field=models.CharField(choices=[('system', 'System'), ('external', 'External')], default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='integrasipesan',
            name='isi_pesan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrasipesan',
            name='waktu',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
