# Generated by Django 5.2 on 2025-06-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyek', '0010_integrasipesan_asal_integrasipesan_isi_pesan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitas',
            name='status',
            field=models.CharField(choices=[('Perencanaan', 'Perencanaan'), ('Berlangsung', 'Berlangsung'), ('Tertunda', 'Tertunda'), ('Berhenti', 'Berhenti'), ('Selesai', 'Selesai')], default='Perencanaan', max_length=20, verbose_name='Status Aktivitas'),
        ),
        migrations.AddField(
            model_name='pekerjaan',
            name='status',
            field=models.CharField(choices=[('Perencanaan', 'Perencanaan'), ('Berlangsung', 'Berlangsung'), ('Tertunda', 'Tertunda'), ('Berhenti', 'Berhenti'), ('Selesai', 'Selesai')], default='Perencanaan', max_length=20, verbose_name='Status Pekerjaan'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Perencanaan', 'Perencanaan'), ('Berlangsung', 'Berlangsung'), ('Tertunda', 'Tertunda'), ('Berhenti', 'Berhenti'), ('siap_dideploy', 'Siap untuk Dideploy'), ('Selesai', 'Selesai')], default='Perencanaan', max_length=20, verbose_name='Status Proyek'),
        ),
    ]
