"""
Django settings for manajemen_proyek project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# BASE_DIR mengarah ke direktori root proyek Django.
BASE_DIR = Path(__file__).resolve().parent.parent

# Pengaturan awal untuk pengembangan
# !!! PENTING: Jangan gunakan kunci ini di produksi! Ganti dengan nilai aman.
SECRET_KEY = 'django-insecure-ln=dz(d)tgb5*1j=yyippb!y^b+w1+qd=e3!xm&ftr5dr0g_9#'

# Debug aktif hanya untuk pengembangan (False = mode produksi)
# Set DEBUG ke False di lingkungan produksi untuk keamanan.
DEBUG = False # Atau True sementara untuk development lokal, lalu False saat deploy

# Host yang diizinkan mengakses aplikasi ini
# Pastikan 'michaelbriant.pythonanywhere.com' ada di sini untuk deployment.
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'michaelbriant.pythonanywhere.com']

# -----------------------------
# Aplikasi yang terdaftar
# -----------------------------
INSTALLED_APPS = [
    # Aplikasi bawaan Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Aplikasi kustom Anda
    'proyek',

    # Aplikasi eksternal
    'widget_tweaks',       # Untuk kustomisasi form di template
    'rest_framework',      # Django REST framework untuk API
    'corsheaders',         # Untuk mengelola Cross-Origin Resource Sharing (CORS)
]

# -----------------------------
# Middleware yang aktif
# -----------------------------
MIDDLEWARE = [
    # CORS middleware harus ditempatkan setinggi mungkin, sebelum middleware lain
    # yang mungkin membaca respons seperti CommonMiddleware atau GZipMiddleware.
    'corsheaders.middleware.CorsMiddleware', # Middleware CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# URL konfigurasi utama
ROOT_URLCONF = 'manajemen_proyek.urls'

# -----------------------------
# Konfigurasi template
# -----------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Direktori khusus tempat menyimpan template HTML
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Processor untuk berbagai kebutuhan kontekstual
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Aplikasi WSGI (untuk server berbasis WSGI seperti gunicorn)
WSGI_APPLICATION = 'manajemen_proyek.wsgi.application'

# -----------------------------
# Database
# -----------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Gunakan SQLite (bawaan)
        'NAME': BASE_DIR / 'db.sqlite3',         # Lokasi file database
    }
}

# -----------------------------
# Validasi Password
# -----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # Panjang minimum
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # Cek password umum
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', # Hindari angka saja
    },
]

# -----------------------------
# Bahasa dan Zona Waktu
# -----------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Jakarta'
USE_I18N = True    # Aktifkan terjemahan
USE_TZ = True      # Gunakan timezone-aware datetime

# -----------------------------
# File statis (CSS, JS, Gambar)
# -----------------------------
STATIC_URL = 'static/'                          # URL prefix
STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # Lokasi collectstatic
STATICFILES_DIRS = [                            # Lokasi tambahan file statis (manual)
    os.path.join(BASE_DIR, 'proyek/static'),
]

# -----------------------------
# File media (upload pengguna)
# -----------------------------
MEDIA_URL = '/media/'                           # URL prefix untuk media
MEDIA_ROOT = BASE_DIR / 'media'                 # Lokasi penyimpanan media

# -----------------------------
# Login dan Redirect
# -----------------------------
LOGIN_URL = '/login/'                           # URL login jika belum login
LOGIN_REDIRECT_URL = '/homepage/'               # Arah setelah berhasil login

# -----------------------------
# Django REST Framework
# -----------------------------
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',         # Output API sebagai JSON
        'rest_framework.renderers.BrowsableAPIRenderer', # Antarmuka API browser
    ],
    # DEFAULT_AUTHENTICATION_CLASSES dan DEFAULT_PERMISSION_CLASSES tidak disetel di sini
    # yang berarti secara default, API Anda akan mengizinkan akses publik (AllowAny)
    # jika tidak ada permission_classes yang didefinisikan di ViewSet/APIView.
    # Untuk produksi, sangat direkomendasikan untuk menambahkan autentikasi dan izin.
}

# -----------------------------
# Konfigurasi CORS (Cross-Origin Resource Sharing)
# -----------------------------
# Mengizinkan semua origin untuk mengakses API. Ini penting untuk aplikasi Android Anda.
# PENTING: Untuk produksi, disarankan untuk mengatur CORS_ALLOWED_ORIGINS
# ke daftar domain/IP yang spesifik untuk keamanan yang lebih baik.
CORS_ALLOW_ALL_ORIGINS = True

# -----------------------------
# Tipe field default untuk primary key
# -----------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'